steps:
  # Verify environment variables
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Verifying environment variables..."
        echo "SUPABASE_URL: ${_SUPABASE_URL:0:10}... (length: ${#_SUPABASE_URL})"
        echo "SUPABASE_KEY: ${_SUPABASE_KEY:0:10}... (length: ${#_SUPABASE_KEY})"
        echo "TWILIO_SID: ${_TWILIO_SID:0:10}... (length: ${#_TWILIO_SID})"
        echo "TWILIO_AUTH_TOKEN: ${_TWILIO_AUTH_TOKEN:0:10}... (length: ${#_TWILIO_AUTH_TOKEN})"
        echo "TWILIO_PHONE: ${_TWILIO_PHONE:0:10}... (length: ${#_TWILIO_PHONE})"
        echo "N8N_CHAT_WEBHOOK: ${_N8N_CHAT_WEBHOOK:0:10}... (length: ${#_N8N_CHAT_WEBHOOK})"
        echo "OPENAI_API_KEY: ${_OPENAI_API_KEY:0:10}... (length: ${#_OPENAI_API_KEY})"
        echo "OPENAI_ASSISTANT_ID: ${_OPENAI_ASSISTANT_ID:0:10}... (length: ${#_OPENAI_ASSISTANT_ID})"
        
        [[ -z "${_SUPABASE_URL}" ]] && echo "ERROR: _SUPABASE_URL is not set" && exit 1
        [[ -z "${_SUPABASE_KEY}" ]] && echo "ERROR: _SUPABASE_KEY is not set" && exit 1
        [[ -z "${_TWILIO_SID}" ]] && echo "ERROR: _TWILIO_SID is not set" && exit 1
        [[ -z "${_TWILIO_AUTH_TOKEN}" ]] && echo "ERROR: _TWILIO_AUTH_TOKEN is not set" && exit 1
        [[ -z "${_TWILIO_PHONE}" ]] && echo "ERROR: _TWILIO_PHONE is not set" && exit 1
        [[ -z "${_N8N_CHAT_WEBHOOK}" ]] && echo "ERROR: _N8N_CHAT_WEBHOOK is not set" && exit 1
        [[ -z "${_OPENAI_API_KEY}" ]] && echo "ERROR: _OPENAI_API_KEY is not set" && exit 1
        echo "All required environment variables are set."

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/tactile-sentry-452823-f7/github.com/mlynnf123/javascript-node:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/tactile-sentry-452823-f7/github.com/mlynnf123/javascript-node:$COMMIT_SHA']
  
  # Create a .env file for the container
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Creating .env file for the container..."
        echo "SUPABASE_URL=${_SUPABASE_URL}" > .env
        echo "SUPABASE_KEY=${_SUPABASE_KEY}" >> .env
        echo "TWILIO_SID=${_TWILIO_SID}" >> .env
        echo "TWILIO_AUTH_TOKEN=${_TWILIO_AUTH_TOKEN}" >> .env
        echo "TWILIO_PHONE=${_TWILIO_PHONE}" >> .env
        echo "N8N_CHAT_WEBHOOK=${_N8N_CHAT_WEBHOOK}" >> .env
        echo "OPENAI_API_KEY=${_OPENAI_API_KEY}" >> .env
        echo "OPENAI_ASSISTANT_ID=${_OPENAI_ASSISTANT_ID}" >> .env
        echo "PORT=3000" >> .env
        echo ".env file created with the following variables:"
        cat .env | grep -v "KEY\|TOKEN\|SID" || true

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'javascript-node'
      - '--image'
      - 'gcr.io/tactile-sentry-452823-f7/github.com/mlynnf123/javascript-node:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'TWILIO_SID=${_TWILIO_SID},TWILIO_AUTH_TOKEN=${_TWILIO_AUTH_TOKEN},TWILIO_PHONE=${_TWILIO_PHONE},SUPABASE_URL=${_SUPABASE_URL},SUPABASE_KEY=${_SUPABASE_KEY},OPENAI_API_KEY=${_OPENAI_API_KEY},OPENAI_ASSISTANT_ID=${_OPENAI_ASSISTANT_ID},N8N_CHAT_WEBHOOK=${_N8N_CHAT_WEBHOOK}'

# Store images in Google Container Registry
images:
  - 'gcr.io/tactile-sentry-452823-f7/github.com/mlynnf123/javascript-node:$COMMIT_SHA'

# Substitution variables for environment variables
# These will be set in the Google Cloud Build trigger
substitutions:
  _TWILIO_SID: ''
  _TWILIO_AUTH_TOKEN: ''
  _TWILIO_PHONE: ''
  _SUPABASE_URL: ''
  _SUPABASE_KEY: ''
  _OPENAI_API_KEY: ''
  _OPENAI_ASSISTANT_ID: ''
  _N8N_CHAT_WEBHOOK: ''
